### ISSUE TITLE
每次切换到列表界面都会自动播放

### ISSUE THREAD

**Issue by zhiquanchi** [52fisher/xiaomusicUI#3]
每次切换到列表界面都会自动播放，就算是设置了暂停也会变成自动播放。

**Comment by 52fisher** [comment]
目前就是这样设定的:对audio标签的功能进行hook，资源地址最初置空，从缓存中获取数据，使用autoplay更改src后能够实现边缓存边自动播放。如果改逻辑也可以，但是一些安卓的浏览器(尤其是国产浏览器)Webview版本太低，不同版本跨度特别大，不确定是否有兼容性问题。
